<script lang="ts">
 import { onMount } from 'svelte';
 import { Plus, Search, RefreshCw, Archive, ArrowRight, Check, X, Play, Pause, RotateCcw, FileText, ChevronRight } from '@lucide/svelte';
 import { workspaces } from '$lib/stores/app';
 import { locale,board,boardReady,boardBusy,boardError,loadBoard,changeBoard,snapshots,integrationErrors } from '$lib/control-center/state';
 import { translated as t,STEPS,COLUMNS,stepLabel,sortChain,formatTime,type Change } from '$lib/control-center/model';
 import Status from '$lib/components/control-center/Status.svelte';
 let source=$state('local'),query=$state(''),archive=$state(false),creating=$state(false),selected=$state('');
 let title=$state(''),description=$state(''),workspace=$state(''),note=$state('');
 let tasks=$derived($board.tasks.filter(v=>(archive?v.state==='archived':v.state!=='archived')&&v.title.toLowerCase().includes(query.toLowerCase())));
 let detail=$derived($board.tasks.find(v=>v.id===selected));
 let remote=$derived(sortChain($snapshots.anneal?.items??[]).filter(v=>`${v.title} ${v.chain_name}`.toLowerCase().includes(query.toLowerCase())));
 async function create(){const okay=await changeBoard({operation:'create',workspace_id:workspace,title,description});if(okay){creating=false;title='';description='';selected=$board.tasks.at(-1)?.id??'';}}
 async function change(c:Change){if(await changeBoard(c))note='';}
 function choose(id:string){selected=id;note='';creating=false;}
 onMount(()=>{void loadBoard();});
</script>
<section class="cc-page cc-board-page"><header class="cc-page-heading"><div><h1>{t($locale,'Work board','任務看板')}</h1><p>{t($locale,'From specification to delivery. Keep the evidence beside the work.','從規格到交付，讓工作與依據保持一致。')}</p></div><button class="cc-button primary" disabled={!$boardReady||!$workspaces.length||source!=='local'} onclick={()=>{creating=true;selected='';workspace=$workspaces[0]?.id??'';}}><Plus size={16}/>{t($locale,'New task','新增任務')}</button></header>
 <div class="cc-tabs"><button class:active={source==='local'} onclick={()=>source='local'}>{t($locale,'Local delivery board','本機交付看板')}<span>{$board.tasks.filter(t=>t.state!=='archived').length}</span></button><button class:active={source==='anneal'} onclick={()=>{source='anneal';selected='';creating=false;}}>Anneal<span>{$snapshots.anneal?.items.length??'—'}</span></button></div>
 <div class="cc-toolbar"><label class="cc-search-field"><Search size={17}/><input bind:value={query} placeholder={t($locale,'Filter tasks…','篩選任務…')} aria-label="Filter tasks"/></label>{#if source==='local'}<button class="cc-button ghost" class:selected={archive} onclick={()=>archive=!archive}><Archive size={15}/>{t($locale,'Archive','封存')}</button><button class="cc-icon-btn" disabled={$boardBusy} onclick={()=>void loadBoard()} aria-label="Refresh board"><RefreshCw size={17}/></button>{:else}<a class="cc-button ghost" href="/integrations">{t($locale,'Refresh connection','更新連線')}</a>{/if}</div>
 {#if source==='local'}
 {#if $boardError}<div class="cc-notice red" role="alert">{$boardError}</div>{/if}
 <p class="cc-board-mode"><FileText size={14}/>{t($locale,'Manual checklist · completing a step records your attestation, not an automated test or merge.','手動清單：完成步驟只會記錄你的確認，不代表自動測試或合併。')}</p>
 <div class:with-detail={!!detail||creating} class="cc-board-layout"><div class="cc-kanban">
 {#each archive?[['archived','Archived','已封存'] as const]:COLUMNS as column}<section class="cc-column"><header><span class="cc-column-dot {column[0]}"></span><h2>{t($locale,column[1],column[2])}</h2><span>{tasks.filter(v=>v.state===column[0]).length}</span></header><div class="cc-column-cards">{#each tasks.filter(v=>v.state===column[0]) as task (task.id)}<button class="cc-task-card" class:chosen={selected===task.id} onclick={()=>choose(task.id)}><span class="cc-task-project">{$workspaces.find(w=>w.id===task.workspace_id)?.name??t($locale,'Unlinked workspace','未連結工作區')}</span><strong>{task.title}</strong><span class="cc-task-step">{stepLabel(task.step,$locale)}</span><div class="cc-task-progress"><span style={`width:${task.step/12*100}%`}></span></div><footer><span>{task.step}/12</span><span>{new Date(task.updated_at*1000).toLocaleDateString()}</span></footer></button>{/each}{#if !tasks.some(v=>v.state===column[0])}<div class="cc-column-empty">{t($locale,'No tasks','沒有任務')}</div>{/if}</div></section>{/each}
 </div>
 {#if creating}<aside class="cc-task-detail"><header><h2>{t($locale,'New task','新增任務')}</h2><button class="cc-icon-btn" onclick={()=>creating=false} aria-label="Close new task"><X size={18}/></button></header><form class="cc-form" onsubmit={e=>{e.preventDefault();void create();}}><label>{t($locale,'Workspace','工作區')}<select bind:value={workspace} required>{#each $workspaces as w}<option value={w.id}>{w.name}</option>{/each}</select></label><label>{t($locale,'Task title','任務標題')}<input bind:value={title} maxlength="240" required placeholder={t($locale,'What needs to be delivered?','需要交付甚麼？')}/></label><label>{t($locale,'Specification','規格')}<textarea bind:value={description} rows="7" maxlength="8192" placeholder={t($locale,'Outcome, constraints and acceptance criteria…','目標、限制與驗收條件…')}></textarea></label><p class="cc-help">{t($locale,'Creates a local checklist only. No coding agent is started.','只建立本機清單，不啟動編程 Agent。')}</p><button class="cc-button primary" disabled={$boardBusy}>{t($locale,'Create task','建立任務')}<ArrowRight size={15}/></button></form></aside>
 {:else if detail}<aside class="cc-task-detail"><header><span class="cc-task-project">{t($locale,'TASK DETAILS','任務詳情')}</span><button class="cc-icon-btn" onclick={()=>selected=''} aria-label="Close task"><X size={18}/></button></header><h2>{detail.title}</h2><Status state={detail.state}/>{#if detail.description}<p class="cc-spec-text">{detail.description}</p>{/if}<div class="cc-button-row">{#if detail.state==='backlog'}<button class="cc-button primary" disabled={$boardBusy} onclick={()=>void change({operation:'start',id:detail!.id})}><Play size={14}/>{t($locale,'Start checklist','開始清單')}</button>{:else if detail.state==='in_progress'}<button class="cc-button secondary" disabled={$boardBusy} onclick={()=>void change({operation:'block',id:detail!.id})}><Pause size={14}/>{t($locale,'Mark blocked','標記受阻')}</button>{:else if detail.state==='blocked'}<button class="cc-button secondary" disabled={$boardBusy} onclick={()=>void change({operation:'resume',id:detail!.id})}><Play size={14}/>{t($locale,'Resume checklist','繼續清單')}</button>{/if}<button class="cc-button ghost" disabled={$boardBusy} onclick={()=>void change({operation:detail!.state==='archived'?'restore':'archive',id:detail!.id})}><Archive size={14}/>{t($locale,detail.state==='archived'?'Restore':'Archive',detail.state==='archived'?'還原':'封存')}</button></div>
 <ol class="cc-chain-steps">{#each STEPS as step,i}<li class:complete={i<detail.step} class:current={i===detail.step}><span class="cc-step-number">{#if i<detail.step}<Check size={13}/>{:else}{i+1}{/if}</span><div><strong>{step[$locale==='en'?0:1]}</strong>{#if detail.evidence.find(e=>e.step===i)}<details><summary>{t($locale,'Recorded evidence','已記錄依據')}</summary><p>{detail.evidence.find(e=>e.step===i)?.note}</p></details>{/if}</div></li>{/each}</ol>
 {#if detail.state==='in_progress'}<form class="cc-form cc-record-step" onsubmit={e=>{e.preventDefault();void change({operation:'record_step',id:detail!.id,note});}}><label>{t($locale,'Evidence for this step','此步驟的依據')}<textarea bind:value={note} rows="3" required maxlength="4096" placeholder={t($locale,'Test result, review reference or your explicit attestation…','測試結果、審查參考或你的明確確認…')}></textarea></label><button class="cc-button primary" disabled={$boardBusy||!note.trim()}><Check size={15}/>{t($locale,'Record & complete step','記錄並完成步驟')}</button></form>{/if}
 </aside>{/if}</div>
 {#if !$workspaces.length&&$boardReady}<div class="cc-notice">{t($locale,'Add a workspace from the sidebar before creating a task.','建立任務前，請先從側邊欄新增工作區。')}</div>{/if}
 {:else}
 {#if $integrationErrors.anneal}<div class="cc-notice amber">{t($locale,'Last refresh failed. This snapshot may be stale.','上次更新失敗，狀態可能已過期。')}</div>{/if}
 <section class="cc-panel">{#if !$snapshots.anneal}<div class="cc-empty tall"><FileText size={32}/><h2>{t($locale,'Bring your Anneal board into view','連接你的 Anneal 看板')}</h2><p>{t($locale,'Connect its existing API to read task state, chain ordering and approval gates.','連接現有 API，讀取任務狀態、流程排序及批准關卡。')}</p><a class="cc-button primary" href="/integrations">{t($locale,'Connect Anneal','連接 Anneal')}</a></div>{:else}<div class="cc-table-wrap"><table class="cc-table"><thead><tr><th>{t($locale,'Task','任務')}</th><th>{t($locale,'Chain','流程')}</th><th>{t($locale,'Layer / index','層級／索引')}</th><th>{t($locale,'State','狀態')}</th><th>{t($locale,'Gate','關卡')}</th></tr></thead><tbody>{#each remote as row (row.id)}<tr><td><strong>{row.title||row.id}</strong></td><td>{row.chain_name||'—'}</td><td>{row.chain_layer??'—'} / {row.chain_index??'—'}</td><td><Status state={row.status}/></td><td>{row.requires_attention?t($locale,'Review in Anneal','在 Anneal 審查'):'—'}</td></tr>{/each}</tbody></table>{#if !remote.length}<p class="cc-quiet-empty">{t($locale,'No matching tasks.','沒有相符任務。')}</p>{/if}</div>{/if}</section>{#if $snapshots.anneal?.has_more}<p class="cc-notice amber">{t($locale,'Partial board: first 200 records only.','部分看板：僅顯示前 200 項。')}</p>{/if}<p class="cc-page-footnote">{t($locale,'Read-only snapshot','唯讀狀態')} · {formatTime($snapshots.anneal?.checked_at)}</p>
 {/if}
</section>
