<script lang="ts">
 import { Search, Layers, ArrowUpRight, ShieldCheck } from '@lucide/svelte';
 import { locale,snapshots,integrationErrors } from '$lib/control-center/state';
 import { translated as t,sortAgents,attention,agentBucket,formatTime } from '$lib/control-center/model';
 import Status from '$lib/components/control-center/Status.svelte';
 let query=$state(''),onlyAttention=$state(false);
 let rows=$derived(sortAgents($snapshots.paseo?.items??[]).filter(i=>(!onlyAttention||attention(i))&&`${i.title} ${i.provider} ${i.workspace}`.toLowerCase().includes(query.toLowerCase())));
</script>
<section class="cc-page"><header class="cc-page-heading"><div><h1>{t($locale,'Agent sessions','Agent 會話')}</h1><p>{t($locale,'A read-only view of existing Paseo sessions. Attention comes first.','唯讀檢視現有 Paseo 會話，優先顯示需要處理的項目。')}</p></div><a class="cc-button secondary" href="/integrations">{t($locale,'Connection settings','連線設定')}<ArrowUpRight size={16}/></a></header>
 <div class="cc-toolbar"><label class="cc-search-field"><Search size={17}/><input bind:value={query} placeholder={t($locale,'Filter sessions, providers or paths…','篩選會話、供應商或路徑…')} aria-label="Filter sessions"/></label><label class="cc-check"><input type="checkbox" bind:checked={onlyAttention}/>{t($locale,'Needs attention','需要處理')}</label><span class="cc-muted">{formatTime($snapshots.paseo?.checked_at)}</span></div>
 {#if $integrationErrors.paseo}<div class="cc-notice amber">{t($locale,'Last refresh failed. The displayed snapshot may be stale.','上次更新失敗，目前顯示的狀態可能已過期。')}</div>{/if}
 <section class="cc-panel">{#if !$snapshots.paseo}<div class="cc-empty tall"><Layers size={34}/><h2>{t($locale,'Connect your session directory','連接會話目錄')}</h2><p>{t($locale,'Read an existing Paseo daemon to see real agent sessions here. Nothing is launched automatically.','讀取現有 Paseo Daemon 後，即可在此查看真實會話，不會自動啟動任何 Agent。')}</p><a href="/integrations" class="cc-button primary">{t($locale,'Connect Paseo','連接 Paseo')}</a></div>{:else}<div class="cc-table-wrap"><table class="cc-table"><thead><tr><th>{t($locale,'Session','會話')}</th><th>{t($locale,'Provider','供應商')}</th><th>{t($locale,'State','狀態')}</th><th>{t($locale,'Permissions','待批准')}</th><th>{t($locale,'Attention','注意事項')}</th></tr></thead><tbody>{#each rows as row (row.id)}<tr><td><div class="cc-cell-title"><strong>{row.title||t($locale,'Untitled session','未命名會話')}</strong><small title={row.workspace}>{row.workspace||row.id}</small></div></td><td><span class="cc-provider">{row.provider||'—'}</span></td><td><Status state={row.status}/></td><td>{row.pending_permissions}</td><td><Status state={agentBucket(row)==='done'?'neutral':agentBucket(row)} label={attention(row)?(row.attention_reason||t($locale,'Review in Paseo','在 Paseo 檢查')):'—'}/></td></tr>{/each}</tbody></table>{#if !rows.length}<div class="cc-quiet-empty">{t($locale,'No sessions match this view.','沒有符合此檢視的會話。')}</div>{/if}</div>{/if}
 </section>{#if $snapshots.paseo?.has_more}<div class="cc-notice amber">{t($locale,'Partial directory: showing the first 200 records. Open Paseo for the full list.','部分目錄：最多顯示前 200 項，完整清單請在 Paseo 查看。')}</div>{/if}<footer class="cc-page-footnote"><ShieldCheck size={14}/>{t($locale,'No prompts, permission approvals or run commands are sent from this view.','此檢視不會傳送提示詞、權限批准或執行命令。')}</footer></section>
