<script lang="ts">
 import { Search, Layers, ArrowUpRight, ShieldCheck } from '@lucide/svelte';
 import { locale,snapshots,integrationErrors,liveStatus,refreshLive } from '$lib/control-center/state';
 import { onMount } from 'svelte';
 import { translated as t,sortAgents,attention,agentBucket,formatTime } from '$lib/control-center/model';
 import Status from '$lib/components/control-center/Status.svelte';
 import SourceDetail from '$lib/components/control-center/SourceDetail.svelte';
 let inspectedSource=$state(''),inspectedEndpoint=$state('');
 let sourceDetail=$derived($snapshots.paseo?.endpoint===inspectedEndpoint?$snapshots.paseo?.items.find(i=>i.id===inspectedSource):undefined);
 let query=$state(''),onlyAttention=$state(false);
 let rows=$derived(sortAgents($snapshots.paseo?.items??[]).filter(i=>(!onlyAttention||attention(i))&&`${i.title} ${i.provider} ${i.workspace}`.toLowerCase().includes(query.toLowerCase())));
 let paseoLive=$derived($liveStatus.find(s=>s.source==='paseo'));
 onMount(()=>{ void refreshLive(); const timer=setInterval(()=>{ if(document.visibilityState==='visible') void refreshLive(); },5000); return ()=>clearInterval(timer); });
</script>
<section class="cc-page"><header class="cc-page-heading"><div><h1>{t($locale,'Agent sessions','Agent 會話')}</h1><p>{t($locale,'Live Paseo sessions. Inspect a row to send, resume, cancel or approve.','即時 Paseo 會話。檢視列可發送、恢復、取消或批准。')}</p></div><a class="cc-button secondary" href="/integrations">{t($locale,'Connection settings','連線設定')}<ArrowUpRight size={16}/></a></header>
 <div class="cc-toolbar"><label class="cc-search-field"><Search size={17}/><input bind:value={query} placeholder={t($locale,'Filter sessions, providers or paths…','篩選會話、供應商或路徑…')} aria-label="Filter sessions"/></label><label class="cc-check"><input type="checkbox" bind:checked={onlyAttention}/>{t($locale,'Needs attention','需要處理')}</label><span class="cc-muted">{formatTime($snapshots.paseo?.checked_at)}</span></div>
 {#if paseoLive?.stale || $integrationErrors.paseo}<div class="cc-notice amber">{t($locale,'Connection is stale or the last refresh failed. Do not approve from an expired snapshot.','連線已過期或上次更新失敗，請勿對過期快照做批准。')}</div>{/if}
 <section class="cc-panel">{#if !$snapshots.paseo}<div class="cc-empty tall"><Layers size={34}/><h2>{t($locale,'Connect your session directory','連接會話目錄')}</h2><p>{t($locale,'Read an existing Paseo daemon to see real agent sessions here. Nothing is launched automatically.','讀取現有 Paseo Daemon 後，即可在此查看真實會話，不會自動啟動任何 Agent。')}</p><a href="/integrations" class="cc-button primary">{t($locale,'Connect Paseo','連接 Paseo')}</a></div>{:else}<div class="cc-table-wrap"><table class="cc-table"><thead><tr><th>{t($locale,'Session','會話')}</th><th>{t($locale,'Provider','供應商')}</th><th>{t($locale,'State','狀態')}</th><th>{t($locale,'Permissions','待批准')}</th><th>{t($locale,'Attention','注意事項')}</th></tr></thead><tbody>{#each rows as row (row.id)}<tr><td><div class="cc-cell-title"><button class="cc-button ghost" aria-label={t($locale,`Inspect session ${row.title||row.id}`,`檢視會話 ${row.title||row.id}`)} onclick={()=>{inspectedSource=row.id;inspectedEndpoint=$snapshots.paseo?.endpoint??'';}}>{row.title||t($locale,'Untitled session','未命名會話')}</button><small title={row.workspace}>{row.workspace||row.id}</small></div></td><td><span class="cc-provider">{row.provider||'—'}</span></td><td><Status state={row.status}/></td><td>{row.pending_permissions}</td><td><Status state={agentBucket(row)==='done'?'neutral':agentBucket(row)} label={attention(row)?(row.attention_reason||t($locale,'Review in Paseo','在 Paseo 檢查')):'—'}/></td></tr>{/each}</tbody></table>{#if !rows.length}<div class="cc-quiet-empty">{t($locale,'No sessions match this view.','沒有符合此檢視的會話。')}</div>{/if}</div>{/if}
 </section>{#if $snapshots.paseo?.has_more}<div class="cc-notice amber">{t($locale,'Partial directory: showing the first 200 records. Open Paseo for the full list.','部分目錄：最多顯示前 200 項，完整清單請在 Paseo 查看。')}</div>{/if}<footer class="cc-page-footnote"><ShieldCheck size={14}/>{t($locale,'Inspect a session to run original allowlisted RPCs. Keep-alive does not auto-create agents.','檢視會話以執行原版允許名單 RPC。保活不會自動建立 Agent。')}</footer>{#if sourceDetail && $snapshots.paseo}<SourceDetail item={sourceDetail} snapshot={$snapshots.paseo} source="paseo" onclose={()=>inspectedSource=''}/>{/if}
</section>
