<script lang="ts">
 import {onMount} from 'svelte';
 import {invoke} from '@tauri-apps/api/core';
 import {Activity,ShieldCheck,RefreshCw} from '@lucide/svelte';
 import {workspaces} from '$lib/stores/app';
 import {locale} from '$lib/control-center/state';
 import {translated as t} from '$lib/control-center/model';
 import {createWorkspaceRefresh} from '$lib/workspace-refresh';
 type Binding={id:string;engine:string;endpoint:string;provider:string;model:string;root:string;enabled:boolean;connected:boolean;current_scope_valid:boolean};
 type Mission={binding_id:string;updated_at:number;observed_at:number|null;last_error:string|null;observation:Record<string,unknown>;mission:{spec:{mission_id:string;task_id:string;title:string;engine:string;provider:string;brief:string};phase:string;revision:number;record_id:string|null;run_id:string|null;pending:string|null;quiescent:boolean;reviews:{note:string;accepted:boolean;reviewer_id:string;source:string}[];receipts:Record<string,{action:string;state:string}>}};
 type Execution={revision:number;bindings:Binding[];missions:Mission[];runtime_id:string;has_more?:boolean;total_missions?:number};
 type View={ok:boolean;workspace_id:string;revision:number;tasks:{id:string;title:string;state:string}[];execution:Execution;summary?:string};
 let workspace=$state(''),selected=$state(''),chosenTask=$state(''),chosenBinding=$state('');
 let snapshot=$state<View|null>(null),error=$state(''),notice=$state(''),busy=$state(false),reading=$state(false),observe=$state(false),mounted=$state(false);
 let refresh=$state<((invalidate?:boolean)=>Promise<void>)|null>(null);
 let engine=$state('paseo'),endpoint=$state('ws://127.0.0.1:6767/ws'),provider=$state('claude'),model=$state(''),mode=$state('default');
 let project=$state(''),repo=$state(''),agent=$state(''),duration=$state(60),credential=$state(''),consent=$state(false),allowCodex=$state(false);
 let reviewNote=$state(''),reviewEvidence=$state('');
 let detail=$derived(snapshot?.execution.missions.find(e=>e.mission.spec.mission_id===selected));
 const actions=['create','start','hold','resume','cancel','close'] as const;
 function reset(){selected='';chosenTask='';chosenBinding='';credential='';consent=false;observe=false;snapshot=null;error='';}
 function when(n:number|null|undefined){return n?new Date(n).toLocaleString():'—';}
 function label(s:string){const labels:Record<string,string>={draft:'已準備（本機）',creating:'建立中',ready:'已建立，等待啟動',start_requested:'已要求啟動',running:'來源回報運行中',hold_requested:'已要求暫停',scheduling_held:'已要求停止派工；程序未確認停止',held:'已確認暫停',review_required:'需要審查',changes_requested:'需要修正',accepted:'協調者已接受',close_requested:'已要求關閉',closed:'已確認關閉',unknown:'結果未知，先核對',failed:'來源回報失敗'};return $locale==='en'?s.replaceAll('_',' '):(labels[s]??s);}
 function allowed(action:string,e:Mission){const m=e.mission;if(m.pending)return false;switch(action){case'create':return m.phase==='draft';case'start':return ['ready','changes_requested'].includes(m.phase);case'hold':return ['running','unknown'].includes(m.phase);case'resume':return m.phase==='held';case'cancel':return ['running','scheduling_held','unknown'].includes(m.phase);case'close':return m.quiescent&&['ready','held','review_required','accepted','changes_requested'].includes(m.phase);default:return false;}}
 onMount(()=>{
  const read=createWorkspaceRefresh(async()=>{
   const id=workspace,mission=selected||null;if(!id)throw Error('Select a workspace / 請選擇工作區');reading=true;
   try{const value=await invoke<View>('execution_local_read',{workspaceId:id,missionId:mission,refreshSource:false});if(!value.ok)throw Error(value.summary||'Observation rejected');if(value.workspace_id!==id)throw Error('Workspace changed during response');return value;}finally{reading=false;}
  },value=>{snapshot=value;error='';},e=>{error=String(e);});
  refresh=read.run;mounted=true;
  const timer=setInterval(()=>{if(!document.hidden&&!busy&&workspace){void read.run(false);if(observe&&selected&&detail?.mission.record_id&&!detail.mission.pending)void inspectSource(false);}},5000);
  return()=>{clearInterval(timer);read.stop();credential='';};
 });
 $effect(()=>{if(mounted&&!workspace&&$workspaces.length)workspace=$workspaces[0].id;});
 $effect(()=>{const id=workspace,mission=selected;if(mounted&&refresh&&id){snapshot=null;void mission;void refresh(true);}});
 async function inspectSource(show=true){if(!selected||busy)return;try{const result=await invoke<View>('execution_local_read',{workspaceId:workspace,missionId:selected,refreshSource:true});if(!result.ok)throw Error(result.summary||'Source read refused');if(show)notice=t($locale,'Source observation requested; the returned snapshot may still be older.','已要求來源觀察，回傳快照可能仍是舊資料。');await refresh?.(true);}catch(e){if(show)error=String(e);}}
 async function configure(){if(!snapshot||!consent)return;busy=true;error='';try{
  await invoke('execution_local_provider',{workspaceId:workspace,operation:'configure',expectedRevision:snapshot.execution.revision,bindingId:null,settings:{id:null,engine,endpoint,provider,model,mode,project_id:engine==='anneal'?project:null,repo_id:engine==='anneal'?repo:null,assignee_id:engine==='anneal'?agent:null,max_duration_min:duration,allow_codex:allowCodex,confirm_external_execution:true},credential,confirm:true});credential='';consent=false;notice=t($locale,'Local binding saved. No worker mission was started.','已儲存本機綁定，未啟動任何工作任務。');await refresh?.(true);
 }catch(e){error=String(e);}finally{busy=false;}}
 async function bindingAction(id:string,operation:string){if(operation==='connect'&&!consent){error=t($locale,'Confirm provider execution consent before reconnecting.','重新連線前，請勾選供應商執行同意。');return;}busy=true;try{await invoke('execution_local_provider',{workspaceId:workspace,operation,bindingId:id,credential:operation==='connect'?credential:null,confirm:true});credential='';notice=t($locale,'Admission updated. Disabling admission does not prove an already-running external worker stopped.','准入設定已更新；停用准入不代表已在運行的外部程序已停止。');await refresh?.(true);}catch(e){error=String(e);}finally{busy=false;}}
 async function update(change:Record<string,unknown>,revision:number){busy=true;error='';try{const result=await invoke<{ok:boolean;summary?:string}>('execution_local_update',{workspaceId:workspace,expectedRevision:revision,change,confirm:true});if(!result.ok)throw Error(result.summary||'Operation rejected');notice=t($locale,'Request recorded. Inspect the observed state; do not repeat an uncertain action.','要求已記錄。請核對觀察狀態，不要重複結果未知的操作。');await refresh?.(true);}catch(e){error=String(e);}finally{busy=false;}}
 async function prepare(){if(!snapshot||!chosenTask||!chosenBinding)return;const id=crypto.randomUUID();await update({operation:'agent_prepare',binding_id:chosenBinding,task_id:chosenTask,mission_id:id},snapshot.revision);if(!error)selected=id;}
 async function control(action:string){if(!detail)return;await update({operation:'agent_control',mission_id:selected,request_key:crypto.randomUUID(),action},detail.mission.revision);}
 async function review(accepted:boolean){if(!detail||!reviewNote.trim()||!reviewEvidence.trim())return;await update({operation:'agent_review',mission_id:selected,note:reviewNote,evidence:reviewEvidence.split('\n').map(s=>s.trim()).filter(Boolean),accepted},detail.mission.revision);}
</script>
<section class="cc-page missions">
 <header class="cc-page-heading"><div><h1>{t($locale,'Mission control','任務協調')}</h1><p>{t($locale,'ChatGPT coordinates; approved local providers perform the assigned work.','由 ChatGPT 協調，已批准的本機供應商執行指定工作。')}</p></div><a class="cc-button secondary" href="/work">{t($locale,'Shared work board','共用任務看板')}</a></header>
 <div class="cc-toolbar"><label>{t($locale,'Workspace','工作區')}<select aria-label="Mission workspace" bind:value={workspace} onchange={reset}>{#each $workspaces as w}<option value={w.id}>{w.name}</option>{/each}</select></label><button class="cc-button secondary" disabled={reading||busy||!workspace} onclick={()=>void refresh?.(true)}><RefreshCw size={15}/>{t($locale,'Refresh records','刷新紀錄')}</button><span class="cc-muted">{t($locale,'The workspace MCP listener must be running.','工作區 MCP listener 必須正在運行。')}</span></div>
 {#if error}<p class="cc-notice amber" role="alert">{error}</p>{/if}{#if notice}<p class="cc-notice" role="status">{notice}</p>{/if}
 <p class="cc-notice amber"><ShieldCheck size={16}/>{t($locale,'External agents use their own runner permissions and may consume provider quota. They do not inherit the MCP AppContainer sandbox. Native MCP computer tools do not require a Codex model.','外部 Agent 使用自己的 runner 權限，可能消耗供應商配額，不會自動繼承 MCP AppContainer 沙箱。原生 MCP 電腦工具不需要 Codex 模型。')}</p>
 {#if snapshot}
 <details class="cc-panel provider-form"><summary>{t($locale,'Local provider setup and consent','本機供應商設定及同意')}</summary>
  <form onsubmit={e=>{e.preventDefault();void configure();}}><fieldset disabled={busy}>
   <div class="form-grid"><label>{t($locale,'Engine','引擎')}<select bind:value={engine} onchange={()=>endpoint=engine==='paseo'?'ws://127.0.0.1:6767/ws':'http://127.0.0.1:3000/'}><option value="paseo">Paseo</option><option value="anneal">Anneal</option></select></label><label>{t($locale,'Literal loopback endpoint','本機 loopback 端點')}<input aria-label="Provider endpoint" bind:value={endpoint} required maxlength="512"/></label><label>{t($locale,'Provider / explicit runner','供應商／明確 runner')}<input aria-label="Provider name" bind:value={provider} required maxlength="128"/></label><label>{t($locale,'Configured model','已設定模型')}<input aria-label="Provider model" bind:value={model} required maxlength="128"/></label><label>{t($locale,'Provider mode','供應商模式')}<input bind:value={mode} required maxlength="128"/></label><label>{t($locale,'Duration budget (minutes)','時間預算（分鐘）')}<input type="number" min="1" max="1440" bind:value={duration}/></label></div>
   {#if engine==='anneal'}<div class="form-grid"><label>Anneal project ID<input bind:value={project} required/></label><label>Repository ID<input bind:value={repo} required/></label><label>Assigned agent ID<input bind:value={agent} required/></label></div><p class="cc-muted">{t($locale,'The source worker must use the explicitly selected runner/model and the approved directory. AUTO/INHERIT routing is not silently accepted.','來源工作程序必須使用指定 runner／模型及已批准目錄；不會默認接受 AUTO／INHERIT 選路。')}</p>{/if}
   <label>{t($locale,'Provider credential (RAM only; optional for an explicitly unauthenticated local source)','供應商憑證（只存記憶體；明確無認證的本機來源可留空）')}<input type="password" autocomplete="off" aria-label="Provider credential" bind:value={credential} maxlength="4096"/></label>
   <label class="check"><input type="checkbox" bind:checked={allowCodex}/>{t($locale,'Explicitly allow model-capable Codex quota for this binding','明確允許此綁定使用 Codex 模型配額')}</label>
   <label class="check"><input type="checkbox" aria-label="Approve external provider execution" bind:checked={consent}/>{t($locale,'I approve this source, directory and provider costs. Its external runner permissions apply.','我批准此來源、目錄及供應商費用，並理解外部 runner 權限仍適用。')}</label>
   <button type="submit" class="cc-button primary" disabled={!consent||busy}>{t($locale,'Save local binding','儲存本機綁定')}</button>
  </fieldset></form>
 </details>
 <section class="cc-panel bindings"><h2>{t($locale,'Approved provider bindings','已批准的供應商綁定')}</h2>{#each snapshot.execution.bindings as b}<article><div><strong>{b.engine} · {b.provider} / {b.model}</strong><small>{b.endpoint} · {b.root}</small><code>{b.id}</code><p>{b.enabled&&b.connected?t($locale,'Local consent attached; source health requires an observation.','本機同意已附加，來源健康狀態仍須觀察。'):t($locale,'Not connected — stored missions are retained.','未連線，已儲存任務仍會保留。')}</p></div><button class="cc-button secondary" disabled={busy||!consent} onclick={()=>void bindingAction(b.id,'connect')}>{t($locale,'Reconnect locally','本機重新連線')}</button><button class="cc-button ghost" disabled={busy} onclick={()=>void bindingAction(b.id,'disable')}>{t($locale,'Block new admissions','禁止新准入')}</button></article>{/each}{#if !snapshot.execution.bindings.length}<p class="cc-muted">{t($locale,'No provider is enabled. Opening this page does not start a model.','未啟用供應商。開啟此頁不會啟動模型。')}</p>{/if}</section>
 <section class="cc-panel assignment"><h2>{t($locale,'Assign an existing board task','指派現有看板任務')}</h2><div class="form-grid"><label>{t($locale,'Board task','看板任務')}<select aria-label="Assignment task" bind:value={chosenTask}><option value="">—</option>{#each snapshot.tasks as task}<option value={task.id}>{task.title}</option>{/each}</select></label><label>{t($locale,'Provider binding','供應商綁定')}<select aria-label="Assignment binding" bind:value={chosenBinding}><option value="">—</option>{#each snapshot.execution.bindings.filter(b=>b.enabled&&b.connected&&b.current_scope_valid) as b}<option value={b.id}>{b.engine} · {b.provider} · {b.id}</option>{/each}</select></label></div><button class="cc-button primary" disabled={busy||!chosenTask||!chosenBinding} onclick={prepare}>{t($locale,'Prepare held mission','準備暫停的任務')}</button><p class="cc-muted">{t($locale,'Preparation is local. Create makes an owned source record without an initial prompt; Start is a separate action.','準備只在本機進行。建立會產生自己的來源紀錄，不附初始提示；啟動是另一個獨立操作。')}</p></section>
 <div class="mission-grid"><section class="cc-panel list"><h2>{t($locale,'Persistent missions','持久化任務')}</h2>{#if selected}<button class="cc-button ghost" onclick={()=>selected=''}>{t($locale,'Show recent missions','顯示最近任務')}</button>{/if}{#each snapshot.execution.missions as e}<button class="mission-choice" onclick={()=>selected=e.mission.spec.mission_id}><strong>{e.mission.spec.title}</strong><span>{label(e.mission.phase)}</span><code>{e.mission.spec.mission_id}</code></button>{/each}{#if snapshot.execution.has_more}<p>{t($locale,'Showing the latest 20 missions. Stored older records are retained.','顯示最近 20 項任務；較舊紀錄仍保留。')}</p>{/if}</section>
 <section class="cc-panel detail"><h2><Activity size={18}/>{t($locale,'Observed execution and review','執行觀察及審查')}</h2>{#if detail}<h3>{detail.mission.spec.title}</h3><p><strong>{label(detail.mission.phase)}</strong> · {t($locale,'revision','版本')} {detail.mission.revision}</p><p class="ids">Mission: {selected}<br/>Source: {detail.mission.record_id??'—'}<br/>Run: {detail.mission.run_id??'—'}<br/>{t($locale,'Last source observation','最近來源觀察')}: {when(detail.observed_at)}</p>{#if detail.last_error}<p class="cc-notice amber">{detail.last_error}</p>{/if}
 <div class="actions">{#each actions as action}<button class="cc-button secondary" disabled={busy||!allowed(action,detail)} onclick={()=>void control(action)}>{t($locale,action.charAt(0).toUpperCase()+action.slice(1),({create:'建立來源任務',start:'啟動',hold:'要求暫停',resume:'繼續',cancel:'要求取消',close:'關閉／封存'})[action])}</button>{/each}<button class="cc-button ghost" disabled={busy||!detail.mission.record_id} onclick={()=>void inspectSource()}>{t($locale,'Inspect source','核對來源')}</button><button class="cc-button ghost" disabled={busy||!detail.mission.record_id} onclick={()=>void control('events')}>{t($locale,'Read event metadata','讀取事件資料')}</button></div>
 <label class="check"><input type="checkbox" bind:checked={observe}/>{t($locale,'Observe this source every five seconds while this page is visible (no automatic work submission)','此頁可見時每五秒觀察來源（不自動派發工作）')}</label><p class="cc-muted">{t($locale,'A hold request is not proof a worker stopped. Anneal Hold blocks subsequent scheduling; Cancel targets its known run. Reconnection never repeats a Start.','要求暫停不代表工作程序已停止。Anneal Hold 阻止後續排程，Cancel 指向已知 run。重新連線不會重複啟動。')}</p>
 <details><summary>{t($locale,'Bounded source evidence','有界來源依據')}</summary><pre>{JSON.stringify(detail.observation,null,2)}</pre></details>
 <fieldset disabled={busy||detail.mission.phase!=='review_required'}><legend>{t($locale,'Coordinator review attestation','協調者審查聲明')}</legend><label>{t($locale,'Review note','審查內容')}<textarea aria-label="Mission review note" bind:value={reviewNote} maxlength="4096" rows="3"></textarea></label><label>{t($locale,'Evidence references — one per line','依據參考 — 每行一項')}<textarea aria-label="Mission review evidence" bind:value={reviewEvidence} rows="2"></textarea></label><div class="actions"><button class="cc-button secondary" disabled={!reviewNote.trim()||!reviewEvidence.trim()} onclick={()=>void review(false)}>{t($locale,'Request changes','要求修正')}</button><button class="cc-button primary" disabled={!reviewNote.trim()||!reviewEvidence.trim()} onclick={()=>void review(true)}>{t($locale,'Accept reviewed result','接受已審查結果')}</button></div></fieldset>
 {#each detail.mission.reviews as r}<p class="review">{r.accepted?'✓':'↻'} {r.note}<small>{r.reviewer_id} · {r.source}</small></p>{/each}<p class="cc-muted">{t($locale,'This is an authenticated coordinator attestation, not a fabricated human approval or permission to merge a source repository.','這是已認證協調者的聲明，不是假造人工批准，亦不代表准許合併來源儲存庫。')}</p>
 {:else}<p class="cc-muted">{t($locale,'Select a mission. No control is inferred from a read-only provider directory.','請選擇任務。唯讀供應商目錄不會自動授予控制權。')}</p>{/if}</section></div>
 {/if}
 <footer class="cc-page-footnote">{t($locale,'Closing a mission does not stop the MCP listener. Disabling a binding stops new admission, not an already-running external process. Credentials must be reattached locally after Desktop restarts.','關閉任務不會停止 MCP listener。停用綁定只阻止新准入，不會假裝終止外部程序。Desktop 重啟後須在本機重新附加憑證。')}</footer>
</section>
<style>
.missions{max-width:1650px}.missions .cc-panel{padding:1.2rem;margin:1rem 0}.missions h2{font-size:1rem;display:flex;gap:.5rem;align-items:center}.missions label:not(.check){display:flex;flex-direction:column;gap:.4rem;font-size:.85rem}.missions input:not([type=checkbox]),.missions textarea,.missions select{padding:.55rem;border:1px solid var(--border);border-radius:8px;background:var(--card-bg);color:inherit;min-width:0;max-width:100%}.missions textarea{width:100%}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin:1rem 0}.check{display:flex;gap:.5rem;align-items:flex-start;margin:1rem 0;font-size:.85rem}.bindings article{display:flex;flex-wrap:wrap;align-items:center;gap:.6rem;border-top:1px solid var(--border);padding:1rem 0}.bindings article>div{flex:1;min-width:220px}.bindings small,.bindings code{display:block;overflow-wrap:anywhere;font-size:.75rem}.mission-grid{display:grid;grid-template-columns:minmax(220px,320px) minmax(0,1fr);gap:1rem}.mission-choice{display:flex;flex-direction:column;gap:.5rem;width:100%;padding:.9rem;margin:.6rem 0;border:1px solid var(--border);border-radius:10px;text-align:left;background:transparent;color:inherit}.mission-choice code,.ids{overflow-wrap:anywhere;font-size:.75rem}.actions{display:flex;flex-wrap:wrap;gap:.5rem;margin:1rem 0}.missions fieldset{border:0;padding:0}.missions legend{font-weight:600;margin:1rem 0}.missions pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:350px;overflow:auto;font-size:.75rem}.review{padding:.65rem;border-left:3px solid var(--border)}.review small{display:block;font-size:.7rem}.missions .cc-notice{display:flex;gap:.6rem}.missions .cc-muted{font-size:.8rem}@media(max-width:900px){.mission-grid,.form-grid{grid-template-columns:1fr}.missions .list{max-height:400px;overflow:auto}}
</style>
